### ISSUE TITLE
Migration Database

### ISSUE THREAD

**Issue by chroda** [slimphp/Tutorial-First-Application#13]
@lornajane can you or anyone who did the migration right just put the .sql here?

Guess is more simple and fast to make things up.

thanks.

**Comment by akrabat** [comment]
It uses the [Phinx](https://phinx.org) migrations system. Look here: [https://github.com/slimphp/Tutorial-First-Application/blob/master/db/migrations/20160111202556_tickets_table.php](https://github.com/slimphp/Tutorial-First-Application/blob/master/db/migrations/20160111202556_tickets_table.php)

**Comment by chroda** [comment]
I notice that, thank you.
