### ISSUE TITLE
Not redirecting tickets page by default

### ISSUE THREAD

**Issue by SiddharthaSarma** [slimphp/Tutorial-First-Application#15]
When ever a user redirects to default URL then it shows **Page Not Found**.
I wasted so much time to figure it out what is the issue with the application.
At last, I found out that the problem with the routes. So I feel it's better to redirect to tickets page.

Please let me if you want to implement this. I will create a merge request for this.
Thanks :)

**Comment by ghost** [comment]
Yup, example is broken. Please update this repo using https://github.com/slimphp/Slim-Skeleton as the base (Slim v3.9)  and maybe update https://www.slimframework.com/docs/tutorial/first-app.html too. Thanks!

**Comment by i-programmer** [comment]
@SiddharthaSarma @anaggh 

it's weird that developers didn't update their first app archive.
Anyway, I uploaded  a working version to clouds:

Maybe it will help  someone

[Moderated to remove links. Please provide GitHub/BitBucket/GitLab links only]

**Comment by odan** [comment]
As a starting point, please check the newer Slim-Skeleton repo: <https://github.com/slimphp/Slim-Skeleton>
Closing this as resolved.
